spring:
  data:
    mongodb:
      #uri: mongodb://wise:123456@192.168.6.201:27017/wise_base_data
      uri: mongodb://wise:123456@192.168.42.29:27018/wise_base_data
server:
  port: 18091
dubbo:
  application:
    name: wise_base_data
    owner: wise_base_data
    organization: hanshow
  registry:
    address: zookeeper://192.168.2.53:2181
#      username: admin
#      password: admin
#      host: 192.168.42.29
#      port: 27017
#      database: springboot-db
