/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanshow_wise_base_privileges_lience_HSLienceProvider */

#ifndef _Included_com_hanshow_wise_base_privileges_lience_HSLienceProvider
#define _Included_com_hanshow_wise_base_privileges_lience_HSLienceProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanshow_wise_base_privileges_lience_HSLienceProvider
 * Method:    getHspk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hanshow_wise_base_privileges_lience_HSLienceProvider_getHspk
  (JNIEnv *, jobject);

/*
 * Class:     com_hanshow_wise_base_privileges_lience_HSLienceProvider
 * Method:    getValue
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_hanshow_wise_base_privileges_lience_HSLienceProvider_getValue
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
