/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HSLienceProvider */

#ifndef _Included_HSLienceProvider
#define _Included_HSLienceProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HSLienceProvider
 * Method:    getHspk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_HSLienceProvider_getHspk
  (JNIEnv *, jobject);

/*
 * Class:     HSLienceProvider
 * Method:    getValue
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_HSLienceProvider_getValue
  (JNIEnv *, jobject, jstring, jint);


#ifdef __cplusplus
}
#endif
#endif
